services:
  mariadb:
    image: "mariadb:12"
    restart: 'no'
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      - "3307:3306"
    expose:
      - 3306
  api:
    build:
      context: ./api
      target: builder
    volumes:
      - ./api:/api
    environment:
      PORT: 8000
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      PYTHON_DB_HOST: "mariadb"
      PYTHON_DB_ACC_PORT: 3306
    ports:
      - '8000:8000'
    restart: "no"
    depends_on:
      - mariadb

volumes:
  db_data: